"""add_foreign_keys

Revision ID: 38ac73523ad8
Revises: e4714a01e806
Create Date: 2026-03-14 22:12:57.015543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ac73523ad8'
down_revision: Union[str, Sequence[str], None] = 'e4714a01e806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'claim_checks', 'claims', ['claim_id'], ['id'])
    op.create_foreign_key(None, 'claims', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_constraint(None, 'claim_checks', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
